 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/coupons", type: :request do
  
  # Coupon. As you add validations to Coupon, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Coupon.create! valid_attributes
      get coupons_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      coupon = Coupon.create! valid_attributes
      get coupon_url(coupon)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_coupon_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      coupon = Coupon.create! valid_attributes
      get edit_coupon_url(coupon)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Coupon" do
        expect {
          post coupons_url, params: { coupon: valid_attributes }
        }.to change(Coupon, :count).by(1)
      end

      it "redirects to the created coupon" do
        post coupons_url, params: { coupon: valid_attributes }
        expect(response).to redirect_to(coupon_url(Coupon.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Coupon" do
        expect {
          post coupons_url, params: { coupon: invalid_attributes }
        }.to change(Coupon, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post coupons_url, params: { coupon: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested coupon" do
        coupon = Coupon.create! valid_attributes
        patch coupon_url(coupon), params: { coupon: new_attributes }
        coupon.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the coupon" do
        coupon = Coupon.create! valid_attributes
        patch coupon_url(coupon), params: { coupon: new_attributes }
        coupon.reload
        expect(response).to redirect_to(coupon_url(coupon))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        coupon = Coupon.create! valid_attributes
        patch coupon_url(coupon), params: { coupon: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested coupon" do
      coupon = Coupon.create! valid_attributes
      expect {
        delete coupon_url(coupon)
      }.to change(Coupon, :count).by(-1)
    end

    it "redirects to the coupons list" do
      coupon = Coupon.create! valid_attributes
      delete coupon_url(coupon)
      expect(response).to redirect_to(coupons_url)
    end
  end
end
