 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/variations", type: :request do
  
  # Variation. As you add validations to Variation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Variation.create! valid_attributes
      get variations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      variation = Variation.create! valid_attributes
      get variation_url(variation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_variation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      variation = Variation.create! valid_attributes
      get edit_variation_url(variation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Variation" do
        expect {
          post variations_url, params: { variation: valid_attributes }
        }.to change(Variation, :count).by(1)
      end

      it "redirects to the created variation" do
        post variations_url, params: { variation: valid_attributes }
        expect(response).to redirect_to(variation_url(Variation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Variation" do
        expect {
          post variations_url, params: { variation: invalid_attributes }
        }.to change(Variation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post variations_url, params: { variation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested variation" do
        variation = Variation.create! valid_attributes
        patch variation_url(variation), params: { variation: new_attributes }
        variation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the variation" do
        variation = Variation.create! valid_attributes
        patch variation_url(variation), params: { variation: new_attributes }
        variation.reload
        expect(response).to redirect_to(variation_url(variation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        variation = Variation.create! valid_attributes
        patch variation_url(variation), params: { variation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested variation" do
      variation = Variation.create! valid_attributes
      expect {
        delete variation_url(variation)
      }.to change(Variation, :count).by(-1)
    end

    it "redirects to the variations list" do
      variation = Variation.create! valid_attributes
      delete variation_url(variation)
      expect(response).to redirect_to(variations_url)
    end
  end
end
